require 'open-uri'
require 'json'
require "fanfeedr/version"
require "fanfeedr/error"
require "fanfeedr/client"
require 'fanfeedr/leagues'
require 'fanfeedr/league'
require 'fanfeedr/conferences'
require 'fanfeedr/conference'
